Require imgaug<0.2.7,>=0.2.5
When you install like this (Debian Buster Linux):
`python3 -m pip install -e git+https://github.com/cogstat/cogstat@2.2#egg=cogstat`

You get this error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
```

This should fix it but by keeping albumentations >0.1.12